# Sample .travis.yml for littler
#
# Dirk Eddelbuettel, April 2014

language: c

before_install:
  - sudo add-apt-repository "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -cs)/"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo apt-get update -qq
  - sudo apt-get install --no-install-recommends r-base-dev

install:
  - ./bootstrap
  
script:
  - ./r --version
  - ./r -e'cat("The value of pi is", pi)'

notifications:
  email:
    on_success: change
    on_failure: change

